title: "Will Napolini - Links in Bio"
description: "Modern, responsive links in bio website"
url: "https://willonsuccess.com"
baseurl: "/linkbio.github.io"

# GitHub Pages settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

# SEO settings
author: "Will Napolini"
twitter:
  username: "willnapolini"
social:
  name: "Will Napolini"
  links:
    - "https://twitter.com/willnapolini"
    - "https://instagram.com/willnapolini"
    - "https://github.com/willnapolini"
